version: '3.7'
services:
  web:
    container_name: sveltekit
    environment:
      - ORIGIN=http://localhost:3000
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
